version: "3"
services:
  frontend:
    build: ./frontend
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - todo-app
  backend:
    build: ./Backend
    ports:
      - "8080:8080"
    networks:
      - todo-app
networks:
  todo-app:
    driver: bridge
